tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/fuse"
tap "homebrew/science"
tap "homebrew/services"
tap "luckyframework/lucky"
tap "mapbox/cli"
tap "pothosware/pothos"
tap "rcmdnk/file"
cask "osxfuse"
brew "ack"
brew "readline"
brew "asciinema"
brew "autoconf"
brew "autojump"
brew "automake"
brew "isl"
brew "p7zip"
brew "ssdeep"
brew "binwalk"
brew "colordiff"
brew "coreutils"
brew "libevent"
brew "libyaml"
brew "crystal-lang"
brew "curl"
brew "libgpg-error"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "docker", link: false
brew "ettercap"
brew "ffmpeg", args: ["with-sdl2"]
brew "figlet"
brew "foremost"
brew "fzf"
brew "gettext"
brew "gist"
brew "git"
brew "git-flow"
brew "git-standup"
brew "gnupg"
brew "go"
brew "gpg-agent"
brew "gx"
brew "gx-go"
brew "htop"
brew "hub"
brew "icecast"
brew "icoutils"
brew "libtool"
brew "imagemagick"
brew "ipfs"
brew "memcached"
brew "libmemcached"
brew "libusb-compat"
brew "libxml2"
brew "mas"
brew "mitmproxy"
brew "mosh"
brew "mtr"
brew "mysql"
brew "nmap"
brew "nvm"
brew "openssl@1.1"
brew "ossp-uuid"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "python"
brew "qemu"
brew "redis", restart_service: true
brew "ripgrep"
brew "sdl2"
brew "speedtest-cli"
brew "sshfs"
brew "sslsplit"
brew "tcpflow"
brew "the_silver_searcher"
brew "tmux"
brew "utf8proc"
brew "wget"
brew "wireshark", link: false
brew "yarn"
brew "heroku/brew/heroku"
brew "luckyframework/lucky/lucky"
brew "rcmdnk/file/brew-file"
cask "adium"
cask "adobe-creative-cloud"
cask "amazon-drive"
cask "amazon-music"
cask "android-studio"
cask "angry-ip-scanner"
cask "anvil"
cask "arq"
cask "atom"
cask "boinc"
cask "bonjour-browser"
cask "chromium"
cask "cocoapods-app"
cask "ultimaker-cura"
cask "discord"
cask "docker"
cask "docker-toolbox"
cask "dropbox"
cask "etcher"
cask "filezilla"
cask "firefox"
cask "geekbench"
cask "github"
cask "google-chrome"
cask "google-earth-pro"
cask "grandperspective"
cask "hipchat"
cask "hyper"
cask "itch"
cask "iterm2"
cask "java"
cask "joinme"
cask "keybase"
cask "kitematic"
cask "little-snitch"
cask "livereload"
cask "lunchy"
cask "macdown"
cask "metasploit"
cask "mono-mdk"
cask "ngrok"
cask "now"
cask "obs"
cask "openemu"
cask "opera"
cask "parallels"
cask "postman"
cask "psequel"
cask "quik"
cask "rescuetime"
cask "sidestep"
cask "sketch"
cask "skitch"
cask "skype"
cask "soundflower"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "transmit"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "wd-firmware-updater"
cask "wireshark"
cask "caskroom/drivers/3dconnexion"
cask "caskroom/drivers/sonos"
cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/fonts/font-menlo-for-powerline"
mas "Blackmagic Disk Speed Test", id: 425264550
mas "CARROT Weather", id: 993487541
mas "CCMenu", id: 603117688
mas "Compressor", id: 424390742
mas "DeskCover", id: 1257711898
mas "DrCleaner", id: 921458519
mas "Earth 3D", id: 476566660
mas "Final Cut Pro", id: 424389933
mas "Frame.io", id: 992958444
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Logic Pro X", id: 634148309
mas "Magnet", id: 441258766
mas "MainStage 3", id: 634159523
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "QuickBooks", id: 640830064
mas "Slack", id: 803453959
mas "Snappy", id: 512617038
mas "Speedtest", id: 1153157709
mas "Trello", id: 1278508951
mas "Unsplash Wallpapers", id: 1284863847
mas "WiFi Explorer", id: 494803304
mas "WiFi Signal", id: 525912054
mas "Xcode", id: 497799835
